import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";

const dosis = Dosis({
  variable: "--font-dosis",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DocMeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dosis.className} antialiased font-dosis `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
